#!/bin/bash
#include <stdio.h>

/**
 * @n: numbers to factor
 * @p: prime number
 * @q: prime number
*/

import math
def factors(number):
	return[(x, number / x)for x in range(int(math.sqrt(number)))[2:] if not number % x]
